import React, { useState } from 'react';
import { ArrowLeft, Sparkles, Upload, FileText, Image as ImageIcon, X, CheckCircle2, Link as LinkIcon, ChevronRight, Loader2, Play, AlertCircle, Radar as RadarIcon, Check } from 'lucide-react';
import { generateGTMResponse } from '../services/geminiService';
import { TAXONOMY } from '../constants';
import { RichSolution, EvaluationData, Solution } from '../types';
import { ResponsiveContainer, RadarChart, PolarGrid, PolarAngleAxis, PolarRadiusAxis, Radar, Tooltip } from 'recharts';

interface SolutionUploadPageProps {
  onBack: () => void;
  onSubmitSuccess: () => void;
  onPublish: (solution: Solution, richDetail: RichSolution, evaluation: EvaluationData) => void;
}

const SolutionUploadPage: React.FC<SolutionUploadPageProps> = ({ onBack, onSubmitSuccess, onPublish }) => {
  const [submitted, setSubmitted] = useState(false);
  const [isImporting, setIsImporting] = useState(false);
  
  // Mandatory Links
  const [links, setLinks] = useState({
    deck: '',
    doc: '',
    pitch: ''
  });

  // Data generated by AI (for Quality Report)
  const [aiEvaluation, setAiEvaluation] = useState<EvaluationData | null>(null);

  // Form State (Populated by AI, Editable by User)
  const [formData, setFormData] = useState({
    title: '',
    version: 'V1.0',
    type: '通用方案', // New: Solution Type
    description: '', // AI Summary
    imageUrl: '', // Cover Image
    
    // Lists
    painPoints: [] as string[],
    architecture: [] as string[],
    highlights: [] as string[], // Value Highlights
    competitiveAdvantage: [] as string[],

    // Tags
    industryL1: '',
    industryL2: '',
    industryL3: '',
    scenarioL1: '',
    scenarioL2: '',
    scenarioL3: '',
    targetRoles: '', // tag.target
    products: '', // tag.product
  });

  // Handlers for Input Change
  const handleLinkChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setLinks({ ...links, [e.target.name]: e.target.value });
  };

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: value }));
  };

  const handleArrayChange = (field: 'painPoints' | 'architecture' | 'highlights' | 'competitiveAdvantage', index: number, value: string) => {
    const newArray = [...formData[field]];
    newArray[index] = value;
    setFormData(prev => ({ ...prev, [field]: newArray }));
  };

  // --- AI Smart Import Logic ---
  const handleSmartImport = async () => {
    if (!links.doc.trim()) {
      alert("请至少填写「方案说明文档」链接以便AI解析内容。");
      return;
    }
    
    setIsImporting(true);
    setAiEvaluation(null); // Reset previous eval

    try {
      // 1. Prepare Taxonomy Context for AI
      const taxonomyContext = JSON.stringify({
        industries: TAXONOMY.INDUSTRIES,
        scenarios: TAXONOMY.SCENARIOS,
        roles: TAXONOMY.ROLES,
        products: TAXONOMY.PRODUCTS
      });

      // 2. Construct Prompt
      const prompt = `
        我是一个GTM方案架构师，正在提报一个新的解决方案。
        请根据我提供的方案文档链接（模拟读取内容）：${links.doc}
        及配套的客户胶片链接：${links.deck} 和 Pitch妙记链接：${links.pitch}。

        请完成以下两项任务：

        【任务一：提取方案元数据】
        请解析并生成以下JSON字段（严格匹配提供的分类体系）：
        - title: 方案名称
        - version: 方案版本（如V1.0）
        - type: 方案类型（如：通用方案、行业方案、大客户定制）
        - description: AI生成的方案摘要（200字以内，突出价值）
        - imageUrl: 封面图URL（如果无法提取，返回 "GENERATE_REQUIRED"）
        - industryL1/L2/L3: 匹配分类体系中的行业（仅返回名称）
        - scenarioL1/L2/L3: 匹配分类体系中的场景（仅返回名称）
        - targetRoles: 匹配分类体系中的关键角色（逗号分隔字符串）
        - products: 匹配分类体系中的涉及产品（逗号分隔字符串）
        - painPoints: 数组，3-4个核心业务痛点
        - architecture: 数组，3-4个方案架构亮点
        - highlights: 数组，3-4个核心价值成效
        - competitiveAdvantage: 数组，3-4个竞争优势
        
        分类体系参考：${taxonomyContext}

        【任务二：AI 质量审核打分】
        请作为“GTM方案质量委员会”，对该方案进行严格审核，并返回以下 evaluation 对象：
        - summary: 评价综述（100字左右）
        - highlights: 方案亮点点评
        - improvements: 待改进建议
        - aiDetails: 数组，包含以下6个维度，每个维度包含 { dimension, weight, score(0-100), evaluation, suggestion }
          维度列表：内容规范及完整性(0.1), 目标客户及故事线(0.2), 业务理解深度与价值(0.3), 方案创新性及AI含量(0.15), 竞争优势及防守策略(0.15), 市场空间及可复制性(0.1)
        - hotWords: { positive: [], neutral: [], negative: [] } // 预测的评价热词

        请务必只返回纯 JSON 格式，不要包含 Markdown 标记。格式结构：
        {
          "metadata": { ...任务一字段 },
          "evaluation": { ...任务二字段 }
        }
      `;

      const responseText = await generateGTMResponse(prompt, []);
      const cleanJson = responseText.replace(/```json/g, '').replace(/```/g, '').trim();
      const data = JSON.parse(cleanJson);

      // 3. Update State
      if (data.metadata) {
        setFormData(prev => ({
          ...prev,
          title: data.metadata.title || '',
          version: data.metadata.version || 'V1.0',
          type: data.metadata.type || '行业方案',
          description: data.metadata.description || '',
          imageUrl: (data.metadata.imageUrl && data.metadata.imageUrl !== 'GENERATE_REQUIRED') ? data.metadata.imageUrl : `https://picsum.photos/800/400?random=${Date.now()}`,
          
          industryL1: data.metadata.industryL1 || '',
          industryL2: data.metadata.industryL2 || '',
          industryL3: data.metadata.industryL3 || '',
          scenarioL1: data.metadata.scenarioL1 || '',
          scenarioL2: data.metadata.scenarioL2 || '',
          scenarioL3: data.metadata.scenarioL3 || '',
          
          targetRoles: data.metadata.targetRoles || '',
          products: data.metadata.products || '',
          
          painPoints: data.metadata.painPoints || ['', '', ''],
          architecture: data.metadata.architecture || ['', '', ''],
          highlights: data.metadata.highlights || ['', '', ''],
          competitiveAdvantage: data.metadata.competitiveAdvantage || ['', '', '']
        }));
      }

      if (data.evaluation) {
        setAiEvaluation(data.evaluation);
      }

    } catch (error) {
      console.error("Import failed", error);
      alert("AI 解析失败，请检查网络或重试。");
    } finally {
      setIsImporting(false);
    }
  };

  const handleSubmit = () => {
    if (!formData.title || !links.doc) {
      alert("请完善方案信息和必填链接");
      return;
    }

    // 1. Create Solution Object (List View)
    const newId = Date.now().toString();
    const solutionSummary: Solution = {
      id: newId,
      title: formData.title,
      description: formData.description,
      author: '我', // Mock current user
      imageUrl: formData.imageUrl || 'https://picsum.photos/400/300?grayscale',
      likes: 0,
      comments: 0,
      favorites: 0,
      date: new Date().toLocaleDateString(),
      industry: formData.industryL1 || '通用',
      version: formData.version,
      tags: {
        industry: [formData.industryL1, formData.industryL2, formData.industryL3].filter(Boolean),
        scene: [formData.scenarioL1, formData.scenarioL2, formData.scenarioL3].filter(Boolean),
        target: formData.targetRoles.split(/,|，/).map(s => s.trim()).filter(Boolean),
        product: formData.products.split(/,|，/).map(s => s.trim()).filter(Boolean)
      },
      isLiked: false,
      isFavorited: false,
      metrics: {
        contentScore: aiEvaluation ? Math.round(aiEvaluation.aiDetails.reduce((acc, i) => acc + i.score * i.weight, 0)) : 80,
        clarityScore: 80,
        depthScore: 80,
        valueScore: 80,
        visualScore: 80
      }
    };

    // 2. Create RichSolution Object (Detail View)
    const solutionDetail: RichSolution = {
      ...solutionSummary,
      painPoints: formData.painPoints,
      architecture: formData.architecture,
      highlights: formData.highlights, // Value Highlights
      competitiveAdvantage: formData.competitiveAdvantage,
      versions: [
        {
          version: formData.version,
          date: new Date().toLocaleDateString(),
          deck: { title: '客户演示胶片.pptx', size: '15MB', link: links.deck },
          doc: { title: '方案说明书.pdf', size: '5MB', link: links.doc },
          pitches: links.pitch ? [{ title: '标准Pitch演练', author: '我', duration: '30min', link: links.pitch }] : []
        }
      ],
      // Add other empty defaults
      website: undefined,
      relatedApps: [],
      relatedDocs: [],
      winningCases: []
    };

    // 3. Evaluation Data
    const evaluationData: EvaluationData = aiEvaluation || {
      summary: '暂无AI评价',
      highlights: '暂无',
      improvements: '暂无',
      aiDetails: [],
      hotWords: { positive: [], neutral: [], negative: [] }
    };

    onPublish(solutionSummary, solutionDetail, evaluationData);

    setSubmitted(true);
    setTimeout(() => {
      onSubmitSuccess();
    }, 2000);
  };

  // Helper to render AI Evaluation Radar
  const renderEvaluation = () => {
    if (!aiEvaluation) return null;
    
    const chartData = aiEvaluation.aiDetails.map(item => ({ subject: item.dimension.slice(0,4), A: item.score, fullMark: 100 }));
    const totalScore = Math.round(aiEvaluation.aiDetails.reduce((acc, item) => acc + (item.score * item.weight), 0));
    
    let gradeColor = 'text-blue-600 bg-blue-50 border-blue-200';
    let grade = 'B';
    if (totalScore >= 90) { grade = 'S'; gradeColor = 'text-purple-600 bg-purple-50 border-purple-200'; }
    else if (totalScore >= 80) { grade = 'A'; gradeColor = 'text-green-600 bg-green-50 border-green-200'; }

    return (
      <div className="bg-white p-6 rounded-xl border border-gray-100 shadow-sm mt-8 animate-fadeIn">
         <div className="flex items-center justify-between mb-6 pb-4 border-b border-gray-100">
            <h3 className="text-lg font-bold text-gray-800 flex items-center gap-2">
               <Sparkles className="text-purple-500" /> AI 方案质量审核报告
            </h3>
            <div className="flex items-center gap-4">
               <span className="text-xs text-gray-400">AI 自动生成，不可修改</span>
               <div className={`px-3 py-1 rounded-lg border ${gradeColor} font-bold text-lg flex items-center gap-2`}>
                  <span>{grade} 级</span>
                  <span className="text-sm font-normal opacity-80">{totalScore}分</span>
               </div>
            </div>
         </div>

         <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <div className="md:col-span-1 h-64 relative">
               <ResponsiveContainer width="100%" height="100%">
                  <RadarChart cx="50%" cy="50%" outerRadius="70%" data={chartData}>
                     <PolarGrid />
                     <PolarAngleAxis dataKey="subject" tick={{fontSize: 10}} />
                     <PolarRadiusAxis angle={30} domain={[0, 100]} tick={false} axisLine={false} />
                     <Radar name="得分" dataKey="A" stroke="#8b5cf6" fill="#8b5cf6" fillOpacity={0.3} />
                     <Tooltip />
                  </RadarChart>
               </ResponsiveContainer>
            </div>
            
            <div className="md:col-span-2 space-y-4">
               <div className="bg-gray-50 p-4 rounded-lg border border-gray-100">
                  <span className="text-xs font-bold text-gray-500 uppercase">评价综述</span>
                  <p className="text-sm text-gray-700 mt-1 leading-relaxed">{aiEvaluation.summary}</p>
               </div>
               <div className="grid grid-cols-2 gap-4">
                  <div className="bg-green-50 p-3 rounded-lg border border-green-100">
                     <span className="text-xs font-bold text-green-700 flex items-center gap-1"><CheckCircle2 size={12}/> 亮点</span>
                     <p className="text-xs text-green-800 mt-1">{aiEvaluation.highlights}</p>
                  </div>
                  <div className="bg-orange-50 p-3 rounded-lg border border-orange-100">
                     <span className="text-xs font-bold text-orange-700 flex items-center gap-1"><AlertCircle size={12}/> 待改进</span>
                     <p className="text-xs text-orange-800 mt-1">{aiEvaluation.improvements}</p>
                  </div>
               </div>
               
               {/* Mini Detail Table */}
               <div className="overflow-x-auto">
                  <table className="w-full text-xs">
                     <thead className="bg-gray-50 text-gray-500">
                        <tr><th className="py-2 text-left pl-2">维度</th><th className="text-center">得分</th><th className="text-left pl-2">建议</th></tr>
                     </thead>
                     <tbody className="divide-y divide-gray-50">
                        {aiEvaluation.aiDetails.slice(0,3).map((d,i) => (
                           <tr key={i}><td className="py-2 pl-2 text-gray-800">{d.dimension}</td><td className="text-center font-bold text-purple-600">{d.score}</td><td className="pl-2 text-gray-500 truncate max-w-[200px]">{d.suggestion}</td></tr>
                        ))}
                     </tbody>
                  </table>
               </div>
            </div>
         </div>
      </div>
    );
  };

  if (submitted) {
    return (
      <div className="p-6 max-w-7xl mx-auto h-full flex items-center justify-center">
        <div className="bg-white p-12 rounded-2xl shadow-sm border border-gray-100 text-center max-w-lg w-full">
          <div className="w-16 h-16 bg-green-100 rounded-full flex items-center justify-center text-green-600 mx-auto mb-6">
            <CheckCircle2 size={32} />
          </div>
          <h2 className="text-2xl font-bold text-gray-900 mb-2">提交成功</h2>
          <p className="text-gray-500 mb-6">您的解决方案已成功提报，并通过了 AI 质量初审。</p>
          <button onClick={onSubmitSuccess} className="bg-lark-500 text-white px-6 py-2 rounded-lg font-medium hover:bg-lark-600 transition">
            返回方案列表
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="p-6 max-w-5xl mx-auto animate-fadeIn pb-24">
      {/* Header */}
      <div className="flex items-center justify-between mb-8">
        <div className="flex items-center gap-4">
          <button onClick={onBack} className="p-2 hover:bg-gray-100 rounded-full transition text-gray-500">
            <ArrowLeft size={20} />
          </button>
          <div>
            <h1 className="text-2xl font-bold text-gray-800">提报新方案</h1>
            <p className="text-sm text-gray-500 mt-1">AI 辅助解析与质量审核，标准化沉淀组织智慧</p>
          </div>
        </div>
        <div className="flex gap-3">
          <button onClick={onBack} className="px-4 py-2 text-gray-600 hover:bg-gray-100 rounded-lg text-sm font-medium transition">取消</button>
          <button 
            onClick={handleSubmit}
            disabled={!aiEvaluation}
            className="px-6 py-2 bg-lark-500 text-white hover:bg-lark-600 rounded-lg text-sm font-medium transition shadow-sm disabled:bg-gray-300 disabled:cursor-not-allowed flex items-center gap-2"
          >
            {aiEvaluation ? <Check size={16}/> : null}
            {aiEvaluation ? '确认提交' : '请先完成AI解析'}
          </button>
        </div>
      </div>

      {/* 1. AI Smart Import Card */}
      <div className="bg-gradient-to-r from-indigo-50 to-white p-6 rounded-xl border border-indigo-100 mb-8 shadow-sm relative overflow-hidden">
         <div className="flex items-center gap-2 mb-6">
             <div className="w-8 h-8 bg-indigo-100 rounded-lg flex items-center justify-center text-indigo-600"><Sparkles size={18} /></div>
             <div>
                <h3 className="text-sm font-bold text-gray-900">AI 智能导入 (必填)</h3>
                <p className="text-xs text-gray-500">输入飞书文档链接，AI 将自动解析内容并进行质量打分</p>
             </div>
         </div>
         
         <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-4">
            <div>
               <label className="block text-xs font-medium text-gray-600 mb-1">客户胶片 (云盘链接) <span className="text-red-500">*</span></label>
               <div className="relative">
                  <Upload size={14} className="absolute left-3 top-2.5 text-gray-400"/>
                  <input type="text" name="deck" value={links.deck} onChange={handleLinkChange} className="w-full pl-8 pr-3 py-2 border border-indigo-100 rounded-lg text-sm focus:ring-1 focus:ring-indigo-500 outline-none bg-white" placeholder="https://..." />
               </div>
            </div>
            <div>
               <label className="block text-xs font-medium text-gray-600 mb-1">方案说明书 (文档链接) <span className="text-red-500">*</span></label>
               <div className="relative">
                  <FileText size={14} className="absolute left-3 top-2.5 text-gray-400"/>
                  <input type="text" name="doc" value={links.doc} onChange={handleLinkChange} className="w-full pl-8 pr-3 py-2 border border-indigo-100 rounded-lg text-sm focus:ring-1 focus:ring-indigo-500 outline-none bg-white" placeholder="https://..." />
               </div>
            </div>
            <div>
               <label className="block text-xs font-medium text-gray-600 mb-1">Pitch 妙记 (妙记链接) <span className="text-red-500">*</span></label>
               <div className="relative">
                  <Play size={14} className="absolute left-3 top-2.5 text-gray-400"/>
                  <input type="text" name="pitch" value={links.pitch} onChange={handleLinkChange} className="w-full pl-8 pr-3 py-2 border border-indigo-100 rounded-lg text-sm focus:ring-1 focus:ring-indigo-500 outline-none bg-white" placeholder="https://..." />
               </div>
            </div>
         </div>

         <div className="flex justify-end">
            <button 
               onClick={handleSmartImport}
               disabled={isImporting || !links.doc}
               className="px-5 py-2 bg-indigo-600 text-white text-sm font-medium rounded-lg hover:bg-indigo-700 disabled:bg-indigo-300 disabled:cursor-not-allowed transition flex items-center gap-2 shadow-sm"
            >
               {isImporting ? <Loader2 size={16} className="animate-spin"/> : <Sparkles size={16} />}
               {isImporting ? 'AI 正在深度解析与评分...' : '开始智能解析'}
            </button>
         </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Main Form Area */}
        <div className="lg:col-span-2 space-y-6">
          
          {/* Section 1: Basic Info */}
          <div className="bg-white p-6 rounded-xl border border-gray-100 shadow-sm">
            <h3 className="text-lg font-bold text-gray-800 mb-4 border-l-4 border-lark-500 pl-3">基本信息 (AI 自动填充)</h3>
            <div className="space-y-5">
              <div className="grid grid-cols-3 gap-4">
                <div className="col-span-2">
                  <label className="block text-sm font-medium text-gray-700 mb-1">方案名称 <span className="text-red-500">*</span></label>
                  <input 
                    type="text" 
                    name="title"
                    value={formData.title}
                    onChange={handleInputChange}
                    className="w-full px-4 py-2 border border-gray-200 rounded-lg focus:ring-1 focus:ring-lark-500 outline-none transition font-bold"
                  />
                </div>
                <div>
                   <label className="block text-sm font-medium text-gray-700 mb-1">版本号</label>
                   <input 
                    type="text" 
                    name="version"
                    value={formData.version}
                    onChange={handleInputChange}
                    className="w-full px-4 py-2 border border-gray-200 rounded-lg focus:ring-1 focus:ring-lark-500 outline-none transition"
                  />
                </div>
              </div>
              
              {/* Hierarchy: Industry */}
              <div className="bg-gray-50 p-4 rounded-lg border border-gray-100">
                <label className="block text-sm font-medium text-gray-800 mb-2">所属行业</label>
                <div className="flex gap-2">
                   <input type="text" name="industryL1" value={formData.industryL1} onChange={handleInputChange} placeholder="一级行业" className="flex-1 px-3 py-2 border border-gray-200 rounded bg-white text-sm" />
                   <input type="text" name="industryL2" value={formData.industryL2} onChange={handleInputChange} placeholder="二级行业" className="flex-1 px-3 py-2 border border-gray-200 rounded bg-white text-sm" />
                   <input type="text" name="industryL3" value={formData.industryL3} onChange={handleInputChange} placeholder="三级行业" className="flex-1 px-3 py-2 border border-gray-200 rounded bg-white text-sm" />
                </div>
              </div>

              {/* Hierarchy: Scenario */}
              <div className="bg-gray-50 p-4 rounded-lg border border-gray-100">
                <label className="block text-sm font-medium text-gray-800 mb-2">适用场景</label>
                <div className="flex gap-2">
                   <input type="text" name="scenarioL1" value={formData.scenarioL1} onChange={handleInputChange} placeholder="一级场景" className="flex-1 px-3 py-2 border border-gray-200 rounded bg-white text-sm" />
                   <input type="text" name="scenarioL2" value={formData.scenarioL2} onChange={handleInputChange} placeholder="二级场景" className="flex-1 px-3 py-2 border border-gray-200 rounded bg-white text-sm" />
                   <input type="text" name="scenarioL3" value={formData.scenarioL3} onChange={handleInputChange} placeholder="三级场景" className="flex-1 px-3 py-2 border border-gray-200 rounded bg-white text-sm" />
                </div>
              </div>

              <div className="grid grid-cols-2 gap-4">
                 <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">匹配关键角色</label>
                  <input type="text" name="targetRoles" value={formData.targetRoles} onChange={handleInputChange} className="w-full px-4 py-2 border border-gray-200 rounded-lg focus:ring-1 focus:ring-lark-500 outline-none transition" />
                </div>
                 <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">涉及产品</label>
                  <input type="text" name="products" value={formData.products} onChange={handleInputChange} className="w-full px-4 py-2 border border-gray-200 rounded-lg focus:ring-1 focus:ring-lark-500 outline-none transition" />
                </div>
              </div>
            </div>
          </div>

          {/* Section 2: Detailed Content */}
          <div className="bg-white p-6 rounded-xl border border-gray-100 shadow-sm relative">
            <h3 className="text-lg font-bold text-gray-800 mb-4 border-l-4 border-lark-500 pl-3">方案详情</h3>
            
            <div className="space-y-6">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">AI 方案摘要</label>
                <textarea 
                  name="description"
                  value={formData.description}
                  onChange={handleInputChange}
                  rows={4}
                  className="w-full px-4 py-3 border border-gray-200 rounded-lg focus:ring-1 focus:ring-lark-500 outline-none transition resize-none leading-relaxed bg-gray-50"
                ></textarea>
              </div>

              <div className="grid grid-cols-2 gap-6">
                 <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">业务痛点 (Pain Points)</label>
                    <div className="space-y-2">
                       {formData.painPoints.map((val, idx) => (
                          <input key={`pp-${idx}`} type="text" value={val} onChange={(e) => handleArrayChange('painPoints', idx, e.target.value)} className="w-full px-3 py-2 border border-gray-200 rounded text-sm" placeholder={`痛点 ${idx+1}`} />
                       ))}
                    </div>
                 </div>
                 <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">方案架构 (Architecture)</label>
                    <div className="space-y-2">
                       {formData.architecture.map((val, idx) => (
                          <input key={`arch-${idx}`} type="text" value={val} onChange={(e) => handleArrayChange('architecture', idx, e.target.value)} className="w-full px-3 py-2 border border-gray-200 rounded text-sm" placeholder={`架构点 ${idx+1}`} />
                       ))}
                    </div>
                 </div>
                 <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">价值成效 (Value)</label>
                    <div className="space-y-2">
                       {formData.highlights.map((val, idx) => (
                          <input key={`hl-${idx}`} type="text" value={val} onChange={(e) => handleArrayChange('highlights', idx, e.target.value)} className="w-full px-3 py-2 border border-gray-200 rounded text-sm" placeholder={`价值 ${idx+1}`} />
                       ))}
                    </div>
                 </div>
                 <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">竞争优势 (Advantage)</label>
                    <div className="space-y-2">
                       {formData.competitiveAdvantage.map((val, idx) => (
                          <input key={`ca-${idx}`} type="text" value={val} onChange={(e) => handleArrayChange('competitiveAdvantage', idx, e.target.value)} className="w-full px-3 py-2 border border-gray-200 rounded text-sm" placeholder={`优势 ${idx+1}`} />
                       ))}
                    </div>
                 </div>
              </div>
            </div>
          </div>
        </div>

        {/* Sidebar: Attachments */}
        <div className="lg:col-span-1 space-y-6">
          <div className="bg-white p-6 rounded-xl border border-gray-100 shadow-sm">
            <h3 className="text-lg font-bold text-gray-800 mb-4">封面设置</h3>
            <div className="rounded-lg overflow-hidden border border-gray-200 mb-4">
               {formData.imageUrl ? <img src={formData.imageUrl} alt="Cover" className="w-full h-40 object-cover" /> : <div className="h-40 bg-gray-100 flex items-center justify-center text-gray-400">暂无图片</div>}
            </div>
            <input 
               type="text" 
               name="imageUrl" 
               value={formData.imageUrl} 
               onChange={handleInputChange} 
               placeholder="输入图片URL或等待AI生成"
               className="w-full px-3 py-2 border border-gray-200 rounded text-xs text-gray-500" 
            />
          </div>
        </div>
      </div>

      {/* READ-ONLY AI EVALUATION SECTION */}
      {renderEvaluation()}

    </div>
  );
};

export default SolutionUploadPage;